### ISSUE TITLE
Node should not need redeploy if AccessToken cannot be retrieved

### ISSUE THREAD

**Issue by belveder79** [stfnhmplr/node-red-contrib-homee#14]
Hi,

first thanks for all the effort you put into this - highly appreciated ;-)

I still have some issue with the HomeeApi node. What I tried to do is to deploy a flow while the Homee is NOT running. The problem in this situation is that this line here

https://github.com/stfnhmplr/node-red-contrib-homee/blob/28e091ef9d4894fa7722b1a7aff78666e4ae624f/nodes/homee.js#L29

triggers a connect, which eventually fails as the Homee is not online and the AccessToken cannot be retrieved here (other repo):

https://github.com/stfnhmplr/homee-api/blob/f4c229ce7bdeb74ed5f8eaa1ffe7424ebac68712/homee.js#L127

This means that the flow is deployed but stuck and never gets out, as the "retry-reconnect" is only happening in the openWs function (afterwards, which never gets called). 

I see two ways to fix this, one is to recursively retry the get AccessToken function, like

`setTimeout(() => this.connect(), this.reconnectInterval * this.retries);`

somewhere around here (other repo again):

https://github.com/stfnhmplr/homee-api/blob/f4c229ce7bdeb74ed5f8eaa1ffe7424ebac68712/homee.js#L132

The other way was to enable an active call to retry connect in 

https://github.com/stfnhmplr/node-red-contrib-homee/blob/28e091ef9d4894fa7722b1a7aff78666e4ae624f/nodes/homee-api.js

Does that make sense?

Cheers
Clemens

**Comment by belveder79** [comment]
here:

https://github.com/stfnhmplr/node-red-contrib-homee/blob/28e091ef9d4894fa7722b1a7aff78666e4ae624f/nodes/homee-api.js#L46

something like this actually works:

```JS
    this.on('input', (msg) => {
      if(typeof msg.topic !== 'undefined') {
        node.error('TOPIC is set!');
        if(msg.topic === 'control') {
          if(msg.payload === 'connect') {
            homee.connect();
          }
        }
      } else {
        homee.send(msg.payload);
      }
    });
```

sending something like

`msg = {'payload':'connect','topic':'control'};`

**Comment by stfnhmplr** [comment]
Hi Clemens, thanks for pointing this out. I think that your first suggestion would be a good solution. I'll create a patch within the next week.

**Comment by stfnhmplr** [comment]
This should be patched now with homee-api v. 0.16.0 (required by 0.7.1 of this plugin). The update should show up in node-red in a few hours.
