### ISSUE TITLE
No message for new Eltako FT55 wireless pushbutton

### ISSUE THREAD

**Issue by Falfango** [stfnhmplr/node-red-contrib-homee#25]
![new](https://user-images.githubusercontent.com/88393695/128046999-66b0d612-0329-4d55-8587-8cf5554f07bf.jpg)
![old](https://user-images.githubusercontent.com/88393695/128047008-088817be-20a8-4ad3-bd84-679d8c32b47b.jpg)
Hi,
I added a new FT55 to homee. Within homee it works. But I do not get any message in node-red from this new one. I added a picture of the new FT55 and a second, which I have added to homee in April, which works in node-red with your node well. As you can see, this looks different within homee. So maybe, there has been a change with one of the last updates of homee. Both FT55 are single button.

**Comment by stfnhmplr** [comment]
The messages are independent of the device type or its properties. Even if there have been a change in the device profile, this should not have any effect on the web socket messages.

Maybe something went wrong during the teach-in-process. You could try to delete the device and add it again. If that does not help, please reach out to the [homee community](https://community.hom.ee). There are several people who have the FT55 in use.
