### ISSUE TITLE
object will notbe created in future versions - please report to developer

### ISSUE THREAD

**Issue by SmartHomer0** [stfnhmplr/node-red-contrib-homee#31]
Hallo zusammen,

untenstehende Meldungen bekomme ich nach Neustart:

homee-Adapter: 
v1.2.0

Systemumgebung:
`PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:1501 MHz
Modell:Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM:7.6 GB
System-Betriebszeit:11 T. 04:37:18
Node.js:v14.19.2
time:1652620420931
timeOffset:-120
Adapter-Anzahl:410
NPM:v6.14.17
Datenträgergröße:251.9 GB
freier Festplattenspeicher:194.8 GB
Betriebszeit:00:00:56
Aktive Instanzen:10
Pfad:/opt/iobroker/
`

Braucht ihr noch zusätzliche Angaben?

`<html><body>

homee.0 | 506 | 2022-05-15 15:13:15.210 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | -- | --
homee.0 | 506 | 2022-05-15 15:13:15.209 | warn | Object  homee.0.DimmableExtendedColorLight-335.Color-1286 is invalid:  obj.common.min is only allowed on obj.common.type "number" or "mixed",  received "string"
homee.0 | 506 | 2022-05-15 15:13:15.200 | warn | This object will not be created in future versions. Please report this to the developer.
homee.0 | 506 | 2022-05-15 15:13:15.197 | warn | Object  homee.0.DimmableExtendedColorLight-12.Color-85 is invalid:  obj.common.min is only allowed on obj.common.type "number" or "mixed",  received "string"
homee.0 | 506 | 2022-05-15 15:13:15.178 | warn | This object will not be created in future versions. Please report this to the developer.
homee.0 | 506 | 2022-05-15 15:13:15.210 | warn | This object will not be created in future versions. Please report this to the developer.
homee.0 | 506 | 2022-05-15 15:13:15.209 | warn | Object  homee.0.DimmableExtendedColorLight-335.Color-1286 is invalid:  obj.common.min is only allowed on obj.common.type "number" or "mixed",  received "string"
homee.0 | 506 | 2022-05-15 15:13:15.200 | warn | This object will not be created in future versions. Please report this to the developer.
homee.0 | 506 | 2022-05-15 15:13:15.197 | warn | Object  homee.0.DimmableExtendedColorLight-12.Color-85 is invalid:  obj.common.min is only allowed on obj.common.type "number" or "mixed",  received "string"
homee.0 | 506 | 2022-05-15 15:13:15.178 | warn | This object will not be created in future versions. Please report this to the developer.
homee.0 | 506 | 2022-05-15 15:13:15.175 | warn | Object  homee.0.DimmableExtendedColorLight-142.Color-550 is invalid:  obj.common.min is only allowed on obj.common.type "number" or "mixed",  received "string"
homee.0 | 506 | 2022-05-15 15:13:15.175 | warn | Object  homee.0.DimmableExtendedColorLight-142.Color-550 is invalid:  obj.common.min is only allowed on obj.common.type "number" or "mixed",  received "string"

</body>
</html>`

**Comment by stfnhmplr** [comment]
This is not related to the Node-RED Module, but the ioBroker Plugin.
