### ISSUE TITLE
Keine Profile

### ISSUE THREAD

**Issue by MehrCurry** [stfnhmplr/node-red-contrib-homee#6]
Hallo,
 
ich habe die Beta installiert und versuche nun Knoten anzulegen.

Leider zeigt die DropDown Box für die Profile nix an. Funktionert das erst, wenn die Homee-in-Homee Verbindung aufgebaut wurde?

Redmatic 5.3.5 auf der CCU3

Guido

**Comment by stfnhmplr** [comment]
You have to configure a virtualHomee first. Then the profiles will be available. See [https://github.com/stfnhmplr/node-red-contrib-homee/blob/dev/README.md](https://github.com/stfnhmplr/node-red-contrib-homee/blob/dev/README.md)
