### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by ckuever** [stfnhmplr/node-red-contrib-homee#9]
Hi,

i always receive the error URIError: URI malformed as described here:

https://community.hom.ee/t/iobroker-homee-instanz-verliert-verbindung/27359/29

iobroker homee adapter is logging the following.

node-red.0 | 2020-04-21 15:52:46.710 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
-- | -- | -- | --
node-red.0 | 2020-04-21 15:52:46.710 | error | at HomeeDeviceNode.Node._emitInput (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
node-red.0 | 2020-04-21 15:52:46.710 | error | at HomeeDeviceNode.on [as _inputCallback] (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-homee/nodes/homeeDevice.js:65:32)
node-red.0 | 2020-04-21 15:52:46.710 | error | at Array.forEach (<anonymous>)
node-red.0 | 2020-04-21 15:52:46.710 | error | at Object.keys.forEach (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-homee/nodes/homeeDevice.js:68:18)
node-red.0 | 2020-04-21 15:52:46.710 | error | at HomeeDeviceNode.updateAttribute (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-homee/nodes/homeeDevice.js:146:68)
node-red.0 | 2020-04-21 15:52:46.710 | error | at Device.statusString (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-homee/lib/device.js:31:28)
node-red.0 | 2020-04-21 15:52:46.710 | error | at Array.map (<anonymous>)
node-red.0 | 2020-04-21 15:52:46.710 | error | at attributes.map (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-homee/lib/device.js:33:36)

maybe you have an idea?

thank you.

**Comment by stfnhmplr** [comment]
The error occurs due to the following entry in the configuration of the attributes: `"unit": "n%Fa",`
This expression is invalid, correct would be `"unit": "n%2Fa",`

You can easily change this in the affected devices. But I will also release a fix in addition.
